baseURL = 'https://havijw.github.io/jackhaviland.com/'
RelativeURLs = true
CanonifyURLs = true
languageCode = 'en-us'
title = 'Jack Haviland'
theme = 'unbloated'


[menu]
  [[menu.main]]
    name = "Home"
    url = ""
    weight = 1
  [[menu.main]]
    name = "Math"
    url = "/math"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[params]
  footer = "&copy; Jack Haviland 2023"
